[package]
name = "kingslayer-web"
version = "0.1.0"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
edition = "2021"

[dependencies]
axum = "0.5"
tokio = { version = "1.21", features = ["full"] }
tower-http = { version = "0.1", features = ["full"] }
