[package]
name = "kingslayer-wasm"
version = "0.1.0"
authors = ["Maxwell Anderson <zaechus@pm.me>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
kingslayer = "0.5"
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"
