[package]
name = "kingslayer-wasm"
version = "0.1.0"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kingslayer = { path = "../../kingslayer" }
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
